// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlk_ivkVZZNsO_ISdoOvTNMkNci35zAjE',
    appId: '1:992354695095:web:09694c0e6911c2ff1fda32',
    messagingSenderId: '992354695095',
    projectId: 'rush-cash-a44fc',
    authDomain: 'rush-cash-a44fc.firebaseapp.com',
    storageBucket: 'rush-cash-a44fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClKkK8Ff7HJkMewYcKQgB6RKjCh9Ykt7Q',
    appId: '1:992354695095:android:90ec22c7b073b40a1fda32',
    messagingSenderId: '992354695095',
    projectId: 'rush-cash-a44fc',
    storageBucket: 'rush-cash-a44fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn0eEm8wTiI41j8y9adHabu7aom9OLoew',
    appId: '1:992354695095:ios:3267aea9e160d5e31fda32',
    messagingSenderId: '992354695095',
    projectId: 'rush-cash-a44fc',
    storageBucket: 'rush-cash-a44fc.appspot.com',
    iosClientId: '992354695095-m9imqpuc3pe0ul0i47t8vnalv04mhh19.apps.googleusercontent.com',
    iosBundleId: 'com.kreiseck.rushcash',
  );
}
